[package]
name = "zkevm-circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_02_02" }
eth-types = { path = "../eth-types" }
halo2curves = { git = 'https://github.com/privacy-scaling-explorations/halo2curves.git', tag = "0.3.1" }
rand_xorshift = "0.3"
rand = "0.8"
rand_chacha = "0.3"
sha3 = "0.10"
log = "0.4.17"
gadgets = { path = "../gadgets"}
plotters = { version="0.3.4" , optional = true}
anyhow = "1.0.68"
lazy_static = "1.4.0"
trace-parser = { path = "../trace-parser" }

[features]
default = ["plot"]
plot = ["dep:plotters", "halo2_proofs/dev-graph"]