{
 "title": "bench",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "test_id", "query": "test_id" }
  ]
 },
 "panels": [
  {
   "title": "memory_usage-${test_id}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "bench_test",
     "rawSql": "SELECT UNIX_TIMESTAMP(`timestamp`) as time, utilizationgb FROM bench_test.testresults_memory_time WHERE test_id = '${test_id}' "
    }
   ]
  },
  {
   "title": "cpu_usage-${test_id}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "bench_test",
     "rawSql": "SELECT UNIX_TIMESTAMP(`timestamp`) as time, utilizationall FROM bench_test.testresults_cpu_time WHERE test_id = '${test_id}' "
    }
   ]
  },
  {
   "title": "bench_result",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "bench_test",
     "rawSql": "SELECT * FROM bench_test.testresults_circuit_benchmark ORDER BY test_date DESC LIMIT 50 "
    }
   ]
  }
 ]
}